export const actions = {
  FETCH_IMAGE_HERO_HEADER_REQUEST: "FETCH_IMAGE_HERO_HEADER_REQUEST",
  FETCH_IMAGE_HERO_HEADER_SUCCESS: "FETCH_IMAGE_HERO_HEADER_SUCCESS",
  FETCH_IMAGE_HERO_HEADER_FAILURE: "FETCH_IMAGE_HERO_HEADER_FAILURE",
};
